# Site
title:              Cosmological Horizon
name:                "Raviteja uppalapati"
description:        "Data Scientist turned Manager at American Express with 8+ years of experience in building scalable text based algorithms and digital products. Interested in the application of machine learning and computational techniques to niche areas like material and drug discovery."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
linkedin:            in/raviteja-uppalapati/
facebook:           uppalapati.teja
instagram:          raviteja936
github:             raviteja936

# personal
location:           Jersey City, NJ
phone:              +1 551-254-5200
email:              uppalapati.teja@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: ""

collections:
  aboutme:
#
# defaults:
# - scope:
#     path: ""
#     type: posts
#   values:
#     permalink: "/blog/:title/"
#     layout: post
#     author:
#     title: "Cosmos"

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
